# -*- yaml -*-
#
# michael a.g. aïvázis
# orthologue
# (c) 1998-2020 all rights reserved
#

dist: bionic
# cmake 3.12
# gcc 7.4
# https://docs.travis-ci.com/user/reference/bionic/

language: python
python:
  - 3.7
  - 3.8

#addons:
  #apt:
    #packages:
      #- python3.7-dev
      #- python3.8-dev

install:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTING=y -DCMAKE_INSTALL_PREFIX=$(realpath ../install)
  - make install

script:
  - ctest --verbose

# end of file
